version: "3"
services: 

  pg:    
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres.conf:/var/lib/postgresql/data/postgresql.conf

    networks:
      - webnet
    ports:
      - "5432:5432"  
    environment:  
       POSTGRES_PASSWORD: example    
       PGDATA: =/tmp	


networks:
  webnet:
